version: "3.9"

services:
  db:
    image: postgres:15
    container_name: patients_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patients_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  patients_service:
    build: .
    container_name: patients_service
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patients_db
      POSTGRES_HOST: db
    ports:
      - "8000:8000"

volumes:
  db_data:
